### ISSUE TITLE
only supported import of SVG with a single path on the top level

### ISSUE THREAD

**Issue by nicolasdb** [WebSVG/voronoi#16]
I just discover this repo, this is very interesting but... I'd like to help by describing some issues and solutions I had wile testing. 

### SVG
1. I have tested with a simple circle or square with a specific size, default layer, nothing fancy from inkscape 1.0 but I received this error: `only supported import of SVG with a single path on the top level`

It worked when I saved the file as `Optimized SVG`, _"inkscape svg" and "plain svg" does not_
Not sure what options are important but It worked with:
![image](https://user-images.githubusercontent.com/12049360/95655504-20087080-0b08-11eb-9e1a-f7cf4d0e7a46.png)
![image](https://user-images.githubusercontent.com/12049360/95655510-30b8e680-0b08-11eb-8bc8-ba6c2cca746e.png)

2. then I don't understand well the units because I don't get the result I'm looking for. 
I'm working in mm, so here is the square I'm testing with: 
![image](https://user-images.githubusercontent.com/12049360/95655690-5bf00580-0b09-11eb-98a8-c3b9c29afd13.png)
it's a 85/85mm page with a 80/80mm square centered.

The result is: 
 ![image](https://user-images.githubusercontent.com/12049360/95655743-af625380-0b09-11eb-82fa-531bc624894b.png)

So I understand that the size in the page is maybe in pixels or without unit. That's fine, I just need to adjust accordingly.

![image](https://user-images.githubusercontent.com/12049360/95656074-197bf800-0b0c-11eb-80cd-4adb4d2e34a9.png)

But I'm not sure how it work then. 
Why there is no seeds on top and left sides?

**Comment by nicolasdb** [comment]
Ah, and I'm testing under Brave browser (which is based on chrome), without any script blockers

**Comment by nicolasdb** [comment]
Strange, now I'm testing with a circle. The "optimized svg" doens't work anymore.
![image](https://user-images.githubusercontent.com/12049360/95656211-03226c00-0b0d-11eb-8800-d40c1820b15e.png)

the square outline is: 
`<svg width="425mm" height="425mm" version="1.1" viewBox="0 0 425.01 425.01" xmlns="http://www.w3.org/2000/svg"><path d="m12.5 12.5h400.01v400.01h-400.01z" fill="none" stop-color="#000000" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.6119"/></svg>`

The circle is: 
`<svg width="400" height="400" version="1.1" viewBox="0 0 105.83 105.83" xmlns="http://www.w3.org/2000/svg"><g transform="translate(-24.067 -55.817)"><path d="m111.58 103.11a39.688 39.688 0 0 1-39.687 39.687 39.688 39.688 0 0 1-39.688-39.687 39.688 39.688 0 0 1 39.688-39.688 39.688 39.688 0 0 1 39.687 39.688z" fill="none" stop-color="#000000" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.247"/></g></svg>
`

Could it be the "transformation" function?

**Comment by nicolasdb** [comment]
yes. 
This is working:
`<svg width="400" height="400" version="1.1" viewBox="0 0 105.83 105.83" xmlns="http://www.w3.org/2000/svg"><path d="m111.58 103.11a39.688 39.688 0 0 1-39.687 39.687 39.688 39.688 0 0 1-39.688-39.687 39.688 39.688 0 0 1 39.688-39.688 39.688 39.688 0 0 1 39.687 39.688z" fill="none" stop-color="#000000" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.247"/></g></svg>
`

So, what do you use to create your SVG? 
Because it feel difficult to get the file right.

**Comment by nicolasdb** [comment]
## PNG
Must be a non-transparent png. no alpha channel. 
Gray levels on white background.

**Comment by wassfila** [comment]
Hi @nicolasdb 
Thank you for your interest in this project, it is indeed a project I had a lot of fun developing and not very common to see such svg interactivity in projects. Usually as soon as it's get complex, then it's done in graphics rendering and not geometrically with vector graphics.
The error you see is a known limitation and even coming from the code of this project not from any other dependency :
https://github.com/WebSVG/voronoi/blob/aa2eaa8a33267e87ec6aae3bea54e6cdbaece921/src/shape.js#L181

For SVG file examples, it's a bit tough, but I directly referred to the SVG standard and created the example SVG by hand :
https://github.com/WebSVG/voronoi/tree/master/data
It should be possible to create samples using other tools, but once you're inside a tool, SVG is tainted with lots of variety, some programs even embed pixel colors inside an SVG to emulate shadows, and when in vectors, there are hundred of ways how to represent the same thing.

I'm doing web and graphics development for fun, not my core know-how, but I'll be glad to help you if you think this tool is useful. I would still have some concerns, this tool is far from being a sw product and is a proof of concept, so might be more relevant for other developers rather than for end users.
If you're interested to understand it as a developer, I'll be glad to explain more.
If you're willing to help by testing and reporting issue, that might still be good to show others what the limitations are, but I do not think I'll be investing effort turning this PoC into a product, who knows maybe someone would then fix these issues with a PR.

**Comment by wassfila** [comment]
I also noticed some selection failures that would be good to fix, if you have more examples you could post them, I have a ticket open for that 
https://github.com/WebSVG/voronoi/issues/11

**Comment by wassfila** [comment]
Back to the main topic, the reason why "only supported import of SVG with a single path on the top level"
is that I'm using a path function to define if a point is in or out, and the complexity grows exponentially if I try either to turn a random SVG into a single path, or if I start looping through all paths in a file, that would not be computationally efficient.

**Comment by wassfila** [comment]
An additional hint, one of the reasons why I did not push this project that much further is that there is an alternative that can be used to produce any sorts of complex SVG, but only if the precision is not needed to be extreemly high, you could work in pixels with any graphics tool and then at the end create an SVG path from any sort of selection.
So if you provide more info about your use case, what did you intend to use this tool for, we might think of enhancements or alternatives.

**Comment by nicolasdb** [comment]
I'm not developer neither, sorry :) 
I was only playing a bit in fusion360 today, to make a custom soap holder, and I wanted to explore with voronoi also. 
![image](https://user-images.githubusercontent.com/12049360/95660565-104d5400-0b29-11eb-82af-6e7d6f214400.png)


So I find quite cool your app, to be able to adjust and constrain how seeds are placed is awesome 👍 
but frustrating when not understanding why it is not working. ^^
So I search a bit and wanted to share what I found. 
Then as soon as limitations are better known, it's easier to play with and it could help or motivate someone to help on the code. _I hope someone will help_

It would be useful to understand how to make svg with inkscape since they have SVG as standard file, it should be easier for most to not have to write themselves the svg. _They have a script for voronoi but quite too basic. 👎_ 
Maybe as a wiki, on this repo. I would be glad to help/test when I can. 

At the end, I tested with the png map from gimp. But there is a lot of potential to understand better how it work. 


Thanks.

**Comment by wassfila** [comment]
@nicolasdb thank you for trying to make the tool better. I will try to help you too. If you want, you can attach the files you created and I'll do the test myself and check why they did not work, or maybe either create the files that work for you and add them to the existing data folder so that you can select them from the drop down menu 
![image](https://user-images.githubusercontent.com/1510763/95663651-5dd5bb00-0b41-11eb-9689-d0755a7e1711.png)


or figure out how to adapt files from Gimp and document that..

**Comment by wassfila** [comment]
your third example is shown as invalid but could get openeed nevertheless
![image](https://user-images.githubusercontent.com/1510763/95663805-6b3f7500-0b42-11eb-967c-015c7aa90b55.png)

it's just a bit small, unit is screen pixels pixels

![image](https://user-images.githubusercontent.com/1510763/95663794-582ca500-0b42-11eb-866b-53cc587870bf.png)

Your square example is working

I have an issue with the display "in cells" function
![image](https://user-images.githubusercontent.com/1510763/95663836-ad68b680-0b42-11eb-872e-6fb077477485.png)

But if you select Shape "avoid path" and Display "all" you get a result without errors, the only down side is that you have to manually delete the outside cells, I did that before and it goes quite quick with fusion
![image](https://user-images.githubusercontent.com/1510763/95663855-e86aea00-0b42-11eb-9f99-2b0e4b0b8610.png)

**Comment by wassfila** [comment]
Here are examples of Fusion360 things I printed from a design with this tool :
![20200418_202622](https://user-images.githubusercontent.com/1510763/95663891-3c75ce80-0b43-11eb-8a03-ebb93e6a604a.jpg)

**Comment by wassfila** [comment]
![20200413_145024](https://user-images.githubusercontent.com/1510763/95663893-44357300-0b43-11eb-8c7e-9bfe48cde209.jpg)

**Comment by wassfila** [comment]
![20200420_224306](https://user-images.githubusercontent.com/1510763/95663896-4992bd80-0b43-11eb-9481-0b3706700a07.jpg)

**Comment by wassfila** [comment]
some models are available on thingiverse
https://www.thingiverse.com/thing:4282292

**Comment by wassfila** [comment]
![20200503_112632](https://user-images.githubusercontent.com/1510763/95663944-b5752600-0b43-11eb-85a0-5440d4e9d572.jpg)

**Comment by wassfila** [comment]
The giraffe was the hardest, I had a bug, so I performed a lot of manual cleaning by selecting Shape "avoid path" and Display "all" then removing out ones by hand.

**Comment by wassfila** [comment]
So if you have an idea in mind, you can show me sketches even drawn by hand or examples and I can help you create the svg files for you and I'll add them as examples.

**Comment by thenickdude** [comment]
For SVGs where Inkscape wrapped my path in a &lt;g> node with a transform, I fixed that by using the Apply Transforms extension:

https://inkscape.org/~Klowner/%E2%98%85apply-transforms

**Comment by wassfila** [comment]
This has been fixed since 0797cb6ccfddd1d3309998374a0c4749b2bf9dc8 so latest version should be fine.
