### ISSUE TITLE
Random color assignment - code fragment

### ISSUE THREAD

**Issue by neuroradiology** [WebSVG/voronoi#18]
First, let me say that this project is awesome! Thanks for creating such an incredible tool for voronoi diagram creation.

Now then... the readme states that random color assignment is a goal. I might have time to look at the source and submit a pull request, but until then, I have a fairly easy way for end users to achieve it.

1) create your voronoi diagram using the online voronoi editor
2) export your diagram to SVG
3) open the SVG in a new browser tab (I testested in Chrome, but should work in Firefox)
4) open the developer tools (default hotkey is \<ctl\>\<shift\>-I
5) make sure you are in the "Console" tab/section of the developer tools
6) paste the following snippet into the console, and hit enter to execute the command

`document.querySelectorAll("path").forEach(function(userPath) {`
`    userPath.setAttribute("fill", "hsl("+ Math.floor(Math.random() * Math.floor(255)) + ",90%,60%)");`
`    userPath.setAttribute("fill-opacity", "40%");`
` })`

This snippet should iterate through all the "path" objects in your document, and set the fill color to:

- a random hue between 0 and 255
- saturation of 90%
- luminosity of 60%
- opacity of 40%

This should be easy to modify to your liking, since the numbers are unique, and the attribute they affect should be clear.

**Comment by wassfila** [comment]
Hi @neuroradiology , thank you for your interest in this project, I had fun indeed developing it.
I could add that snippet myself, but I would let you make the PR so that it's credited with your commit. You can add it in a separate file.
And also, if you're interested for the sake of learning, I can guide you through the steps on how to add it as a button on the GUI.
On the readme of this repo, I added a link to the discord server channel I created for this project among others I worked on, we can discuss there if you're interested to take up the challenge.

**Comment by neuroradiology** [comment]
You are an incredibly gracious maintainer. Wow.

I am humbled by your offer, but you have shamed me into stepping up (in  a good way :p)

A pull request has been submitted. I hope it's sufficiently idiomatic for the remainder of your project.
